INSERT INTO competencia_c8 (nombre, tipo_cs, descripcion, area) VALUES
('Pensamiento espacial y sistemas territoriales', 'Pensamiento espacial', 'Comprensión del espacio geográfico, orientación, lectura de mapas y relación entre territorio y sociedad.', 'Ciencias Sociales'),
('Pensamiento temporal y representaciones sociales', 'Pensamiento temporal', 'Manejo de conceptos de tiempo histórico, cambio, continuidad y memoria colectiva.', 'Ciencias Sociales'),
('Pensamiento social y crítico', 'Pensamiento crítico', 'Análisis de fenómenos sociales, económicos y culturales desde múltiples perspectivas.', 'Ciencias Sociales'),
('Ética, convivencia y ciudadanía', 'Ciudadanía', 'Reconocimiento de derechos, deberes, normas de convivencia y participación democrática.', 'Ciencias Sociales'),
('Relaciones con la historia y la cultura', 'Historia y cultura', 'Comprensión de procesos históricos locales, nacionales y mundiales, y su impacto cultural.', 'Ciencias Sociales'),
('Relaciones ético-políticas', 'Ética política', 'Análisis de estructuras de poder, democracia, derechos humanos y resolución de conflictos.', 'Ciencias Sociales'),
('Relaciones con el ambiente', 'Ambiente', 'Comprensión de la relación sociedad-naturaleza, problemáticas ambientales y desarrollo sostenible.', 'Ciencias Sociales'),
('Relaciones económicas y sociales', 'Economía y sociedad', 'Análisis de sistemas económicos, actividades productivas y organización social.', 'Ciencias Sociales');


INSERT INTO grado (nombre, numero, ciclo, area) VALUES
('Transición', 0, 'Ciclo Inicial', 'Ciencias Sociales'),
('Primero', 1, 'Ciclo 1', 'Ciencias Sociales'),
('Segundo', 2, 'Ciclo 1', 'Ciencias Sociales'),
('Tercero', 3, 'Ciclo 1', 'Ciencias Sociales'),
('Cuarto', 4, 'Ciclo 2', 'Ciencias Sociales'),
('Quinto', 5, 'Ciclo 2', 'Ciencias Sociales'),
('Sexto', 6, 'Ciclo 3', 'Ciencias Sociales'),
('Séptimo', 7, 'Ciclo 3', 'Ciencias Sociales'),
('Octavo', 8, 'Ciclo 4', 'Ciencias Sociales'),
('Noveno', 9, 'Ciclo 4', 'Ciencias Sociales'),
('Décimo', 10, 'Ciclo 5', 'Ciencias Sociales'),
('Undécimo', 11, 'Ciclo 5', 'Ciencias Sociales');

INSERT INTO dba_catalogo (id, grado_id, competencia_id, codigo_men, enunciado_oficial, evidencias_aprendizaje) VALUES
(1, 2, 1, 'CS-G1-DBA1', 'Se ubica en el espacio que habita teniendo como referencia su propio cuerpo y los puntos cardinales.', 'Relaciona su izquierda-derecha, adelante–atrás con los puntos cardinales; dibuja instituciones sociales de su barrio; localiza referentes en representaciones gráficas; describe el recorrido entre su casa y la institución educativa.'),
(2, 2, 1, 'CS-G1-DBA2', 'Describe las características del paisaje geográfico del barrio, vereda o lugar donde vive, sus componentes y formas.', 'Reconoce formas de relieve; diferencia estados del tiempo atmosférico; identifica obras de infraestructura; representa problemas ambientales de la comunidad.'),
(3, 2, 2, 'CS-G1-DBA3', 'Describe el tiempo personal y se sitúa en secuencias de eventos propios y sociales.', 'Nombra días de la semana y meses del año; diferencia ayer, hoy y mañana; identifica miembros de la familia y sus edades relativas.'),
(4, 2, 2, 'CS-G1-DBA4', 'Reconoce la noción de cambio a partir de las transformaciones que ha vivido en los últimos años a nivel personal, familiar y del entorno.', 'Relata acontecimientos del aula; señala transformaciones del entorno físico; describe organizaciones sociales; plantea preguntas sobre sucesos; recuerda fechas de cumpleaños.'),
(5, 2, 3, 'CS-G1-DBA5', 'Reconoce su individualidad y su pertenencia a los diferentes grupos sociales.', 'Identifica sus características físicas; reconoce su nombre y nacionalidad; describe roles en su familia y escuela.'),
(6, 3, 1, 'CS-G2-DBA1', 'Se ubica en el espacio urbano o rural utilizando puntos cardinales y referentes naturales.', 'Utiliza planos para orientarse; identifica límites del municipio; describe elementos naturales y artificiales del paisaje.'),
(7, 3, 1, 'CS-G2-DBA2', 'Identifica las características de los relieves y climas de su departamento.', 'Diferencia montañas, valles y llanuras; asocia el clima con actividades económicas; reconoce fuentes hídricas cercanas.'),
(8, 3, 5, 'CS-G2-DBA3', 'Reconoce que el lugar donde vive es el resultado de procesos históricos y migraciones.', 'Identifica fundadores del municipio; describe cambios en la arquitectura; reconoce tradiciones culturales locales.'),
(9, 3, 4, 'CS-G2-DBA4', 'Comprende la importancia de las normas y autoridades en el municipio.', 'Identifica funciones del alcalde y concejo; propone normas de convivencia escolar; reconoce símbolos patrios locales.'),
(10, 4, 1, 'CS-G3-DBA1', 'Se ubica en representaciones espaciales utilizando coordenadas geográficas.', 'Identifica paralelos y meridianos; localiza Colombia en el globo terráqueo; utiliza la rosa de los vientos en mapas.'),
(11, 4, 1, 'CS-G3-DBA2', 'Comprende las características de la Tierra y el sistema solar.', 'Describe movimientos de rotación y traslación; reconoce planetas del sistema solar; explica la formación de las estaciones.'),
(12, 4, 5, 'CS-G3-DBA3', 'Identifica las culturas indígenas que habitaron el territorio antes de la llegada de los españoles.', 'Describe organización social de Muiscas y Taironas; reconoce legados culturales indígenas; identifica ubicación de cacicazgos.'),
(13, 5, 1, 'CS-G4-DBA1', 'Reconoce los límites y la división política de Colombia.', 'Localiza departamentos y capitales; identifica países vecinos y fronteras marinas; describe la organización territorial.'),
(14, 5, 7, 'CS-G4-DBA2', 'Analiza la biodiversidad de las regiones naturales de Colombia.', 'Diferencia fauna y flora por pisos térmicos; identifica problemas de deforestación; propone acciones de conservación.'),
(15, 5, 5, 'CS-G4-DBA3', 'Comprende el proceso de conquista y colonización del territorio colombiano.', 'Identifica causas de la llegada de europeos; describe el impacto en poblaciones indígenas; reconoce la herencia hispánica.'),
(16, 6, 1, 'CS-G5-DBA1', 'Analiza la importancia del relieve en la economía de las regiones de Colombia.', 'Relaciona producción agrícola con el clima; identifica zonas mineras; describe puertos y vías de comunicación.'),
(17, 6, 8, 'CS-G5-DBA2', 'Comprende las dinámicas de la población en Colombia.', 'Identifica procesos de urbanización; reconoce causas del desplazamiento forzado; analiza censos poblacionales.'),
(18, 6, 5, 'CS-G5-DBA3', 'Analiza el proceso de independencia de Colombia y sus consecuencias.', 'Identifica causas de la independencia; describe batallas principales; reconoce figuras como Bolívar y Santander.'),
(19, 7, 1, 'CS-G6-DBA1', 'Comprende el origen del universo y las teorías sobre la evolución de la Tierra.', 'Explica la teoría del Big Bang; identifica eras geológicas; describe la tectónica de placas.'),
(20, 7, 5, 'CS-G6-DBA2', 'Analiza las civilizaciones antiguas de Mesopotamia, Egipto, Grecia y Roma.', 'Describe organización política antigua; reconoce aportes científicos y artísticos; identifica ubicación geográfica de imperios.'),
(21, 7, 4, 'CS-G6-DBA3', 'Comprende la importancia de los Derechos Humanos en la sociedad actual.', 'Identifica origen de los DDHH; describe mecanismos de protección en Colombia; analiza situaciones de vulneración.'),
(22, 8, 1, 'CS-G7-DBA1', 'Analiza las características de los continentes (Asia, África, Europa, Oceanía).', 'Localiza accidentes geográficos mundiales; compara densidades de población; identifica potencias económicas.'),
(23, 8, 5, 'CS-G7-DBA2', 'Comprende la Edad Media y la transición al Renacimiento.', 'Describe el sistema feudal; explica el papel de la iglesia; reconoce avances del humanismo y la ciencia.'),
(24, 8, 5, 'CS-G7-DBA3', 'Analiza el impacto del descubrimiento de América en la economía global.', 'Describe rutas comerciales coloniales; explica el mestizaje cultural; reconoce la explotación de metales preciosos.'),
(25, 9, 1, 'CS-G8-DBA1', 'Analiza los cambios territoriales en el mundo tras la Revolución Industrial.', 'Explica el crecimiento de ciudades industriales; identifica nuevas fuentes de energía; describe impactos ambientales.'),
(26, 9, 5, 'CS-G8-DBA2', 'Comprende las revoluciones políticas del siglo XVIII y XIX.', 'Analiza la Revolución Francesa; identifica causas de la independencia en América Latina; describe el ascenso de la burguesía.'),
(27, 9, 6, 'CS-G8-DBA3', 'Analiza la formación del Estado-Nación en Colombia durante el siglo XIX.', 'Diferencia proyectos federalistas y centralistas; describe guerras civiles; identifica la Constitución de 1886.'),
(28, 10, 1, 'CS-G9-DBA1', 'Comprende los conflictos territoriales en el mundo durante el siglo XX.', 'Analiza causas de la Primera y Segunda Guerra Mundial; describe el nuevo mapa de Europa; identifica el papel de la ONU.'),
(29, 10, 5, 'CS-G9-DBA2', 'Analiza el impacto de la Revolución Rusa y el ascenso de regímenes totalitarios.', 'Describe el surgimiento de la URSS; identifica características del fascismo y nazismo; analiza consecuencias del Holocausto.'),
(30, 10, 6, 'CS-G9-DBA3', 'Comprende los procesos de modernización en Colombia durante la primera mitad del siglo XX.', 'Describe la danza de los millones; identifica causas de la masacre de las bananeras; analiza el periodo de la República Liberal.'),
(31, 10, 6, 'CS-G9-DBA4', 'Analiza el periodo de La Violencia en Colombia y la formación del Frente Nacional.', 'Identifica causas del asesinato de Gaitán; describe el acuerdo bipartidista; analiza el origen de las guerrillas.'),
(32, 11, 8, 'CS-G10-DBA1', 'Comprende los efectos de la globalización en la economía colombiana.', 'Analiza tratados de libre comercio; identifica el papel de multinacionales; describe el impacto en el agro nacional.'),
(33, 11, 6, 'CS-G10-DBA2', 'Analiza la Constitución Política de 1991 y su importancia para la democracia.', 'Reconoce la tutela como mecanismo de defensa; identifica derechos fundamentales; describe la estructura del Estado actual.'),
(34, 11, 6, 'CS-G10-DBA3', 'Comprende los desafíos de la paz y la reconciliación en la Colombia contemporánea.', 'Analiza el conflicto armado reciente; identifica importancia de la Ley de Víctimas; describe retos del posconflicto.'),
(35, 12, 8, 'CS-G11-DBA1', 'Analiza los sistemas económicos mundiales (capitalismo, socialismo, economía mixta).', 'Compara eficiencia y equidad en modelos económicos; identifica crisis financieras globales; analiza el papel del FMI y Banco Mundial.'),
(36, 12, 6, 'CS-G11-DBA2', 'Comprende las dinámicas políticas de la geopolítica actual.', 'Analiza el papel de potencias emergentes (China, India); identifica conflictos por recursos naturales; describe organismos de integración regional.'),
(80, 12, 3, 'CS-G11-DBA3', 'Analiza las consecuencias políticas, económicas y sociales de algunos conflictos geopolíticos desde finales del siglo XX.', 'Caracteriza conflictos geopolíticos contemporáneos; reconoce dinámicas geopolíticas en relaciones internacionales; describe intereses de grandes potencias; argumenta consecuencias sociales de conflictos internacionales.'),
(81, 12, 5, 'CS-G11-DBA4', 'Comprende las implicaciones sociales, económicas y políticas que tuvo la Guerra Fría en el mundo.', 'Reconoce bloques hegemónicos de la Guerra Fría; explica implicaciones cotidianas de pertenecer a un bloque; interpreta repercusiones de la Guerra Fría en Latinoamérica; plantea argumentos sobre amenazas con armas de destrucción masiva.'),
(82, 12, 8, 'CS-G11-DBA5', 'Analiza la globalización como un proceso que redefine el concepto de territorio, las dinámicas de los mercados y las identidades locales.', 'Reconoce características de la globalización económica y política; explica y sitúa bloques económicos y tratados de integración; describe ventajas y desventajas de la globalización; argumenta papel de organizaciones latinoamericanas de integración.');